/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "MyFirstService.h"
#include "MyFirstService.tcc"

namespace myfirst {


MyFirstService_log_args::~MyFirstService_log_args() throw() {
}


MyFirstService_log_pargs::~MyFirstService_log_pargs() throw() {
}


MyFirstService_multiply_args::~MyFirstService_multiply_args() throw() {
}


MyFirstService_multiply_pargs::~MyFirstService_multiply_pargs() throw() {
}


MyFirstService_multiply_result::~MyFirstService_multiply_result() throw() {
}


MyFirstService_multiply_presult::~MyFirstService_multiply_presult() throw() {
}


MyFirstService_get_log_size_args::~MyFirstService_get_log_size_args() throw() {
}


MyFirstService_get_log_size_pargs::~MyFirstService_get_log_size_pargs() throw() {
}


MyFirstService_get_log_size_result::~MyFirstService_get_log_size_result() throw() {
}


MyFirstService_get_log_size_presult::~MyFirstService_get_log_size_presult() throw() {
}

} // namespace

