/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "myfirst_constants.h"

namespace myfirst {

const myfirstConstants g_myfirst_constants;

myfirstConstants::myfirstConstants() {
  PI = 3.14159;

}

} // namespace

